
DELETE http://localhost:3000/api/v1/students/3
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJqb3NlIiwiZXhwIjoxNjc4MzE3NzE0OTE3LCJpYXQiOjE2NzgzMTc1OTR9.b7MuBdQtj8mQXAuMsKnoUnqx39nSkiwdZRXDEJQoFuk

###

DELETE http://localhost:3000/api/v2/students/7
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJqb3NlIiwiZXhwIjoxNjc4MzE1NjYwODE4LCJpYXQiOjE2NzgzMTU1NDB9.yJWK5fUP8LWOVREsHNx8qgBlAybXedFZlKBa8ZLFN34

###

DELETE http://localhost:3000/api/v3/students/7
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJqb3NlIiwiZXhwIjoxNjc4MzE1NjYwODE4LCJpYXQiOjE2NzgzMTU1NDB9.yJWK5fUP8LWOVREsHNx8qgBlAybXedFZlKBa8ZLFN34