
DELETE http://localhost:3000/api/v1/students/4
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJqb3NlIiwiZXhwIjoxNjc4NDY0MjI3NDc3LCJpYXQiOjE2Nzg0NjQxMDd9.eK_rmHui0fKIa7fSxNIwsFhPdx_80rGUO-sRgzK_0dQ

###

DELETE http://localhost:3000/api/v2/students/7
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJqb3NlIiwiZXhwIjoxNjc4MzE1NjYwODE4LCJpYXQiOjE2NzgzMTU1NDB9.yJWK5fUP8LWOVREsHNx8qgBlAybXedFZlKBa8ZLFN34

###

DELETE http://localhost:3000/api/v3/students/7
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJqb3NlIiwiZXhwIjoxNjc4MzE1NjYwODE4LCJpYXQiOjE2NzgzMTU1NDB9.yJWK5fUP8LWOVREsHNx8qgBlAybXedFZlKBa8ZLFN34