
POST http://localhost:3000/api/v1/students/registrar
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJqb3NlIiwiZXhwIjoxNjc4NDY3Nzk4MjE4LCJpYXQiOjE2Nzg0Njc2Nzh9.2JksMfyNAO07Fd07hHpVeMRj9e2cpiiT9TeGGbiXymk

{
    "name": "gael",
    "age": 3,
    "enroll": "true"
}

###

POST http://localhost:3000/api/v2/students/registrar
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJqb3NlIiwiZXhwIjoxNjc4MzE1NTAyMjA3LCJpYXQiOjE2NzgzMTUzODJ9.H-sGhBmUgYBMaaHU4FqX3FvdVW9rA1ErF6ySpRQuT38

{
    "name": "gael",
    "age": 3,
    "enroll": "true"
}

###

POST http://localhost:3000/api/v3/students/registrar
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsIm5hbWUiOiJqb3NlIiwiZXhwIjoxNjc4MzE1NTAyMjA3LCJpYXQiOjE2NzgzMTUzODJ9.H-sGhBmUgYBMaaHU4FqX3FvdVW9rA1ErF6ySpRQuT38

{
    "name": "gael",
    "age": 3,
    "enroll": "true"
}